- README.rst
- requirements.txt
- setup.py
Remove the requirement of shapely. This lib only relies on shapely_ext from libpysal.
This lib is now successfully released to PyPI. See [pointpats 1.0.0](https://pypi.python.org/pypi/pointpats/1.0.0)
> Make some change for release to PyPI

- setup.py
Similar to https://github.com/pysal/giddy/pull/46 to resolve potential encoding issue
> force UTF8 encoding for the long description read

- .travis.yml
Travis-CI is failing because we try to grab the [dev version of libpysal on github](https://github.com/pysal/libpysal)  https://github.com/pysal/pointpats/blob/master/.travis.yml#L23  while the libpysal API structure is now different from the released pypi version. The current configuration could make the travis testing fail very often as the libpysal API could be changing constantly.
This PR installs stable `libpysal` for travis testing instead of grabbing [pysal/libpysal](https://github.com/pysal/libpysal). Once all the API changes in libpysal are finalized and released to pypi, major changes could then be made to pointpats.
> install stable released libpysal for travis testing

- doc/_static/pysal-styles.css
in response to https://github.com/pysal/submodule_template/pull/11
> fix missing reference labels in rendered sphinx docs

- README.md
- setup.py
This PR is to add README.md to resolve Issue https://github.com/pysal/pointpats/issues/24. The setup.py is also updated to read the markdown file instead of the rst file as the long description for the package. Therefore, README.rst is redundant and can be eventually removed once the notebook book project switches to use the added README.md @darribas
> add README.md to resolve issue #24

- requirements.txt
Add the required version of libpysal for pointpats: libpysal 4.0.0 is the first version released since the refactoring.
> require libpysal>=4.0.0

- .travis.yml
This PR addresses the faulty dual testing schema within `.travis.yml` raised in  pysal/pysal#1145.
> updating dual travis test procdeure

- doc/_static/references.bib
- doc/api.rst
- doc/installation.rst
- pointpats/__init__.py
- pointpats/spacetime.py
- pointpats/tests/test_spacetime.py
- requirements.txt
Move functionalities of space time interaction tests from legacy pysal.spatial_dynamics.interaction to `pointpats`:
address https://github.com/pysal/giddy/issues/124
> Add space time interaction tests

- pointpats/quadrat_statistics.py
This
- runs `black` on `quadrat_statistics.py` 
- allows `QStatistic` to take a numpy array. When the input is a numpy array, the function converts it to a point pattern immediately.
> make quadrat statistics accept a numpy array as argument

- pointpats/geometry.py
- pointpats/ripley.py
close #72 
found a duplicate of the function, changed it there as well.
> handle 0-index simplex in delaunay

- pointpats/geometry.py
- pointpats/ripley.py
This removes duplicated code in `ripley.py` that was intended to be sourced from `geometry.py` when the new `random.py` module was written. This should have been done in #54 but was missed before the merge.
> remove extra material from ripley.py and source from geometry.py

- pointpats/centrography.py
- requirements.txt
As discussed in #80, the required `opencv-contrib-python` is causing issues for pysal downstream packages on conda-forge. Making `opencv-contrib-python` optional can solve the issue. Since `opencv-contrib-python` is only used by one function, it is safe to make it an optional requirement.
> Make opencv package optional

- ci/envs/38-minimal.yaml
- pointpats/geometry.py
- requirements.txt
partially address https://github.com/pysal/pointpats/issues/89
handle scipy's deprecation since v1.8.0:
/Users/runner/work/pointpats/pointpats/pointpats/geometry.py:134: DeprecationWarning: Please use `ConvexHull` from the `scipy.spatial` namespace, the `scipy.spatial.qhull` namespace is deprecated.
> handle scipy deprecation

- .github/workflows/build_docs.yml
- .github/workflows/release_and_publish.yml
- README.md
- setup.py
Add Github actions for release and docs building - resolve part of the infrastructure issue https://github.com/pysal/pointpats/issues/86
> add github action for release and doc building

- pointpats/__init__.py
https://github.com/pysal/pointpats/issues/93
> bump to v2.3.0

- ci/envs/38-minimal.yaml
- pointpats/geometry.py
- pointpats/pointpattern.py
It seems that the DataFrame input to query worked but was never actually supported. This ensures we always cast it to a numpy array.
Closes #106 
We should probably cut a patch release with this as any env with new scipy will have this issue.
> COMPAT: ensure we pass numpy array to cKDtree and combat with sklearn 1.3.0

- pointpats/geometry.py
- pointpats/tests/test_ripley.py
- pointpats/tests/test_spacetime.py
Follow up on #91 reported in #89.
- removing direct invocation of `scipy.spatial.cKDtree` which will be deprecated (use `scipy.spatial.KDtree` instead)
- fixing ConvexHull namespace
- fixing pytest deprecations
> Handle scipy and pytest deprecations

- pointpats/process.py
- pointpats/window.py
I've noticed some warnings about deprecation of `libpysal.cg.shapes`. User cannot do anything about those and we need to refactor pointpats ourselves. So I'm silencing them for now as they only cause confusion.
> silence cg warnings

- pointpats/pointpattern.py
- pointpats/quadrat_statistics.py
Minor enhancements of our plotting code in `PointPattern` and `QStatistic`. 
`QStatistic` now returns the axis so you can do anything you want with it, e.g. add contextily basemap or any other layer. 
`PointPattern` defaults to equal aspect since it is expected that in most cases, coordinates are projected. This does not skew the geography. When they are in lat lon, assuming plate carree should also be a better option than the default ratio. In any case, since you can get `ax` now, you can change it afterwards.
> ENH: return axis when plotting QStatistic, default to equal aspect when plotting PointPattern

- ci/envs/310-latest.yaml
- ci/envs/311-dev.yaml
- ci/envs/311-latest.yaml
- ci/envs/39-latest.yaml
- docs/api.rst
- docs/conf.py
- pointpats/__init__.py
- pointpats/kde.py
- pointpats/tests/test_kde.py
Resolves https://github.com/gdsbook/book/issues/305. Essentially replaces `seaborn.kdeplot` which does not work as expected with our own solution.
Tests will come once I'll figure out how to do them.
```py
import geopandas as gpd
from pointpats.kde import plot_density
gdf = gpd.read_file('https://martinfleischmann.net/sds/chapter_06/data/brno_pedestrian_accidents.gpkg')
gdf.plot(markersize=0.5, figsize=(9,9))
plot_density(gdf, 500)
```
```py
gdf.plot(markersize=0.5, figsize=(9,9))
plot_density(gdf, 500, levels=25, cmap="magma_r", linewidths=1)
```
```py
gdf.plot(markersize=0.1, figsize=(9,9), zorder=2, color='k')
plot_density(gdf, 500, levels=25, cmap="magma_r", fill=True)
```
```py
gdf.plot(markersize=0.5, figsize=(9,9))
plot_density(gdf, 1000, cmap="magma_r", linewidths=1)
```
I would …
> ENH: plot_density for KDE plotting of point patterns based on statsmodels

- pointpats/kde.py
- pointpats/tests/test_kde.py
> right now this gives back a `matplotlib.contour.QuadContourSet`. Is there any way to have it return an axes object, e.g. to play nicely with contextily? (https://github.com/pysal/pointpats/pull/118#issuecomment-1734643715)
Yep.
> plot density on axis

- ci/envs/310-latest.yaml
- ci/envs/311-dev.yaml
- ci/envs/311-latest.yaml
- ci/envs/38-minimal.yaml
- ci/envs/39-latest.yaml
- docs/conf.py
- pointpats/centrography.py
- pointpats/tests/test_centrography.py
Resolves the issue seen in https://github.com/pysal/libpysal/issues/681 where opencv causes installation headache. Since we already depend on shapely, there's no need to depend on OpenCV, so using shapely's minimum_rotated_rectangle, computing the angle manually and coercing the resulting array into the opencv-like order (which is the opposite compared to shapely).
> REF: reimplement mrr on top of shapely

- .github/workflows/tests.yaml
- ci/envs/310-latest.yaml
- ci/envs/310-minimal.yaml
- ci/envs/311-latest.yaml
- ci/envs/312-dev.yaml
- ci/envs/312-latest.yaml
- environment.yml
- pointpats/tests/test_spacetime.py
- pyproject.toml
This PR:
* resolves #139 
* resolves #141
> update min supported Python and testing workflow

- pointpats/distance_statistics.py
- pointpats/tests/test_distance_statistics.py
A simple change that allows us to pass geopandas objects directly onto Ripley's functions without a need of extracting the underlying array of coordinates.
This is a part of #135 that does not need me to learn the dispatch thingy :)
> ENH: support geopandas objects in distance statistics

- pointpats/tests/test_kde.py
matplotlib ContourSet does not have collections in 3.10 so testing needs to be done differently. Does not affect users.
> TST: matplotlib test compatibility

- .gitignore
- docs/api.rst
- pointpats/centrography.py
- pointpats/tests/test_centrography.py
~Very much WIP as I just wanted to see how this actually works. Will continue at some point later on this.~
One thing I wanted to figure out was to ensure that we also support numpy arrays of shapely objects and return a shapely object but it seems that singledispatch typing is a bit limited in this sense and there's no way of distinguishing between `np.ndarray[np.float64]` and `np.ndarray[shapely.Geometry]`. At least none of the attempts I made worked.
xref #135 
TODO:
> ENH: singledispatch in centrography to natively support geopandas objects
